<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>iai_icub_description</name>
  <version>0.0.0</version>
  <description>URDF description of the iCub robot.</description>

  <maintainer email="luc_kro@uni-bremen.de">Luca Krohm</maintainer>
  <author email="dummy@dummy.com">https://github.com/robotology/icub-models</author>
  <license>CC BY-SA 4.0</license>

  <!-- ROS 2 Build & Dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- If using URDF/Xacro -->
  <depend>urdf</depend>
  <depend>xacro</depend>

  <!-- If using SDFormat (Gazebo) -->
  <depend>sdformat_urdf</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>